name: BeerNative
options:
  bundleIdPrefix: fr.eiter
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: BeerNative/Resources/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: fr.eiter.plexibeer
    MARKETING_VERSION: "3.2.1"
    CURRENT_PROJECT_VERSION: "8"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    DEVELOPMENT_TEAM: ""
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig
targets:
  BeerNative:
    type: application
    platform: iOS
    sources:
      - path: BeerNative/Sources
      - path: BeerNative/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: PlexiBeer
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
schemes:
  BeerNative:
    build:
      targets:
        BeerNative: all
    run:
      config: Debug
    archive:
      config: Release